#include "metagen_base_types.c"
#include "metagen_base_memory.c"
#include "metagen_base_math.c"
#include "metagen_base_random.c"
#include "metagen_base_strings.c"
#include "metagen_base_ring.c"
#include "metagen_base_thread_ctx.c"
#include "metagen_base_command_line.c"
